const baseStories=[
{id:'match-5',title:'Match 5: Everything Is on the Line',summary:'The Dark Knights and Ninjas collide in a massive showdown at Castle Hayne.',body:'The season reaches a defining moment as the league leaders meet with standings, pride, and playoff position at stake. Expect aggressive lines, pressure putts, and a full day of Team Clash energy.',category:'Match Preview',date:'2026-07-12',image:'https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?auto=format&fit=crop&w=1200&q=82'},
{id:'knights-win',title:'Knights Take the Win',summary:'A steady back nine closes out a tight team battle.',body:'The Dark Knights stayed composed late and converted the key putts needed to secure the match.',category:'Match Recap',date:'2026-07-08',image:'https://images.unsplash.com/photo-1611821064430-0d40291d0f0b?auto=format&fit=crop&w=1200&q=82'},
{id:'player-spotlight',title:'Player Spotlight: Sam the Silencer',summary:'Quiet confidence, clean releases, and another clutch finish.',body:'This week’s spotlight celebrates the player who let the scorecard do the talking.',category:'League News',date:'2026-07-03',image:'https://images.unsplash.com/photo-1608245449230-4ac19066d2d0?auto=format&fit=crop&w=1200&q=82'},
{id:'castle-hayne',title:'Course Preview: Castle Hayne',summary:'Know the landing zones before match day.',body:'A quick look at the course, risk-reward decisions, and holes most likely to swing the match.',category:'Course Preview',date:'2026-06-29',image:'https://images.unsplash.com/photo-1603872455843-9df8f4fcb609?auto=format&fit=crop&w=1200&q=82'}];
const saved=JSON.parse(localStorage.getItem('tc-published')||'[]');const stories=[...saved,...baseStories];
const teams=[['♞','Dark Knights','4-0'],['🥷','Ninjas','3-1'],['⛓','Chain Breakers','2-2'],['🐺','Iron Wolves','1-3'],['◉','Disc Addicts','0-4']];
const schedule=[['July 20','Dark Knights vs Ninjas','Castle Hayne','9:00 AM'],['July 27','Chain Breakers vs Iron Wolves','Arrowhead','9:00 AM'],['August 3','Disc Addicts vs Dark Knights','Northern Regional','9:30 AM']];
const standings=[['Dark Knights',4,0,12],['Ninjas',3,1,9],['Chain Breakers',2,2,6],['Iron Wolves',1,3,3],['Disc Addicts',0,4,0]];
const app=document.querySelector('#app');document.querySelector('#menu')?.addEventListener('click',()=>document.querySelector('#nav').classList.toggle('open'));
function storyCard(s){return `<article class="story" onclick="location.hash='story/${s.id}'"><img src="${s.image}" alt=""><div class="story-copy"><time>${s.date}</time><h3>${s.title}</h3><p>${s.summary}</p><span class="eyebrow">Read more →</span></div></article>`}
function home(){app.innerHTML=`<section class="hero"><div class="hero-copy"><span class="eyebrow">Featured story</span><h1>${stories[0].title}</h1><p>${stories[0].summary}</p><a class="btn" href="#story/${stories[0].id}">Read story →</a></div></section><section class="shell"><div class="dashboard"><article class="card"><h2 class="eyebrow">Upcoming match</h2><div class="matchup"><div class="team-mark">♞<b>Dark Knights</b></div><div class="versus">VS</div><div class="team-mark">🥷<b>Ninjas</b></div></div><div class="details">📅 Saturday, July 20<br>◷ 9:00 AM<br>⌖ Castle Hayne Disc Golf Course</div><br><a class="btn ghost" href="#schedule">View schedule</a></article><section class="card"><div class="section-title"><h2 class="eyebrow">Latest stories</h2><a class="eyebrow" href="#stories">View all</a></div><div class="story-grid">${stories.slice(1,4).map(storyCard).join('')}</div></section><section class="card"><h2 class="eyebrow">Current standings</h2>${standingsTable()}<br><a class="eyebrow" href="#standings">Full standings →</a></section></div></section>`}
function standingsTable(){return `<table class="table"><thead><tr><th>#</th><th>Team</th><th>W</th><th>L</th><th>PTS</th></tr></thead><tbody>${standings.map((r,i)=>`<tr><td class="rank">${i+1}</td><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td></tr>`).join('')}</tbody></table>`}
function storiesPage(){app.innerHTML=`<section class="page"><h1>Stories & Archive</h1><div class="filters"><input id="search" placeholder="Search stories"><select id="cat"><option value="">All categories</option>${[...new Set(stories.map(x=>x.category))].map(x=>`<option>${x}</option>`).join('')}</select></div><div class="archive-grid" id="results">${stories.map(storyCard).join('')}</div></section>`;const render=()=>{const q=search.value.toLowerCase(),c=cat.value;results.innerHTML=stories.filter(s=>(!c||s.category===c)&&(`${s.title} ${s.summary}`.toLowerCase().includes(q))).map(storyCard).join('')||'<p>No stories found.</p>'};search.oninput=render;cat.onchange=render}
function schedulePage(){app.innerHTML=`<section class="page"><h1>Schedule</h1><div class="schedule-grid">${schedule.map(x=>`<article class="card schedule-item"><div class="date">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}<br>${x[3]}</p></article>`).join('')}</div></section>`}
function standingsPage(){app.innerHTML=`<section class="page"><h1>Standings</h1><article class="card">${standingsTable()}</article></section>`}
function teamsPage(){app.innerHTML=`<section class="page"><h1>Teams</h1><div class="teams-grid">${teams.map(t=>`<article class="card team-card"><div class="team-mark">${t[0]}</div><h2>${t[1]}</h2><p>${t[2]} record</p></article>`).join('')}</div></section>`}
function article(id){const s=stories.find(x=>x.id===id)||stories[0];app.innerHTML=`<article class="page article"><a class="eyebrow" href="#stories">← Stories</a><h1>${s.title}</h1><p class="lead">${s.summary}</p><img src="${s.image}" alt=""><p>${s.body}</p>${s.link?`<p><a class="btn" href="${s.link}" target="_blank">Related link</a></p>`:''}</article>`}
function route(){const h=location.hash.slice(1)||'home',parts=h.split('/');if(parts[0]==='story')article(parts[1]);else ({home,stories:storiesPage,schedule:schedulePage,standings:standingsPage,teams:teamsPage}[h]||home)()}window.addEventListener('hashchange',route);route();
