import {mkdir, writeFile} from 'node:fs/promises';
import {HISTORICAL_RECORD_SOURCES} from '../src/data/historicalRecords.ts';

const OUTPUT_PATH = 'supabase/seed/launch_seed.sql';
const IMPORTED_AT = '2026-07-19T00:00:00.000Z';
const TEAM_LOGOS = {
  'cougar-country': '/team-logos/cougar-country.jpg',
  'hayneous-og-s': '/team-logos/hayneous-ogs.jpg',
  kb: '/team-logos/kb.png',
  ninjas: '/team-logos/ninjas.jpg',
  riptide: '/team-logos/riptide.jpg',
  'wild-turkey': '/team-logos/wild-turkey.jpg',
};
const PLAYER_NAME_ALIASES = new Map([
  ['ariel cosmo', 'Ariel Cosimo'],
  ['cecilia costin', 'CeCelia Costin'],
  ['chad hessenflow', 'Chad Hassenflow'],
  ['isaac kotson', 'Isaac Cotson'],
  ['jodie lehmann', 'Jodie Lehman'],
  ['joshua matheson', 'Josh Matheson'],
]);
const FEMALE_PLAYERS = new Set([
  'alisica fussell',
  'angel mabee',
  'ariel cosimo',
  'ariel cosmo',
  'ashlee hynds',
  'brianna kinsman',
  'candy mcclernan',
  'cecelia costin',
  'crystal fussell',
  'currie istre',
  'jamie hensley',
  'jasmine pollack',
  'jodie lehman',
  'jodie lehmann',
  'kim mchale',
  'lani evans',
  'logan canale',
  'misti lee',
  'nadya gutierrez',
  'nicole pierre',
  'rosa carroll',
  'shannon boney',
  'shannon johnson',
]);

const teams = buildTeams();
const players = buildPlayers();
const statements = [
  '-- Generated by npm run seed:launch:sql',
  '-- Seeds the launch account workflow from imported historical league data.',
  buildTeamInsert(teams),
  buildPlayerAliasCleanup(),
  buildPlayerInsert(players),
].filter(Boolean);

await mkdir('supabase/seed', {recursive: true});
await writeFile(OUTPUT_PATH, `${statements.join('\n\n')}\n`);
console.log(`Wrote ${teams.length} teams and ${players.length} players to ${OUTPUT_PATH}`);

function buildTeams() {
  const teamsByName = new Map();
  const teamShortNames = new Set();

  for (const source of HISTORICAL_RECORD_SOURCES) {
    for (const record of source.teamRecords) {
      const teamName = clean(record.teamName);
      const teamKey = normalize(teamName);
      if (teamsByName.has(teamKey)) continue;

      const id = createSlug(teamName);
      const shortName = createShortName(teamName, teamShortNames);
      teamShortNames.add(normalize(shortName));
      teamsByName.set(teamKey, {
        id,
        name: teamName,
        shortName,
        logo: TEAM_LOGOS[id] ?? '',
        active: true,
        createdAt: IMPORTED_AT,
        updatedAt: IMPORTED_AT,
      });
    }
  }

  return Array.from(teamsByName.values()).sort((first, second) => first.name.localeCompare(second.name));
}

function buildPlayers() {
  const playersByName = new Map();

  for (const source of HISTORICAL_RECORD_SOURCES) {
    for (const record of source.playerRecords) {
      const playerName = canonicalizePlayerName(record.playerName);
      const playerKey = normalize(playerName);
      if (playersByName.has(playerKey)) continue;

      playersByName.set(playerKey, {
        id: createSlug(playerName),
        name: playerName,
        gender: FEMALE_PLAYERS.has(playerKey) ? 'Female' : 'Male',
        pdgaNumber: record.pdgaNumber,
        pdgaRating: record.pdgaRating,
        currentTeamId: null,
        homeArea: '',
        active: true,
        createdAt: IMPORTED_AT,
        updatedAt: IMPORTED_AT,
      });
    }
  }

  return Array.from(playersByName.values()).sort((first, second) => first.name.localeCompare(second.name));
}

function buildPlayerAliasCleanup() {
  const aliasIds = Array.from(PLAYER_NAME_ALIASES.keys(), createSlug);
  if (!aliasIds.length) return '';

  return `delete from public.launch_players
where id in (${aliasIds.map(sqlValue).join(', ')});`;
}

function buildTeamInsert(teamsToSeed) {
  if (!teamsToSeed.length) return '';
  return `insert into public.launch_teams (id, name, short_name, logo, active, created_at, updated_at) values
${teamsToSeed.map((team) => `(${[
    team.id,
    team.name,
    team.shortName,
    team.logo,
  ].map(sqlValue).join(', ')}, ${sqlBool(team.active)}, ${sqlValue(team.createdAt)}, ${sqlValue(team.updatedAt)})`).join(',\n')}
on conflict (id) do update set
  name = excluded.name,
  short_name = excluded.short_name,
  logo = excluded.logo,
  active = excluded.active,
  updated_at = excluded.updated_at;`;
}

function buildPlayerInsert(playersToSeed) {
  if (!playersToSeed.length) return '';
  return `insert into public.launch_players (id, name, gender, pdga_number, pdga_rating, current_team_id, home_area, active, created_at, updated_at) values
${playersToSeed.map((player) => `(${[
    player.id,
    player.name,
    player.gender,
    player.pdgaNumber,
    player.pdgaRating,
    player.currentTeamId,
    player.homeArea,
  ].map(sqlValue).join(', ')}, ${sqlBool(player.active)}, ${sqlValue(player.createdAt)}, ${sqlValue(player.updatedAt)})`).join(',\n')}
on conflict (id) do update set
  name = excluded.name,
  gender = excluded.gender,
  pdga_number = excluded.pdga_number,
  pdga_rating = excluded.pdga_rating,
  current_team_id = excluded.current_team_id,
  home_area = excluded.home_area,
  active = excluded.active,
  updated_at = excluded.updated_at;`;
}

function createSlug(value) {
  return clean(value)
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function canonicalizePlayerName(playerName) {
  const cleanedName = clean(playerName);
  return PLAYER_NAME_ALIASES.get(normalize(cleanedName)) ?? cleanedName;
}

function createShortName(teamName, usedShortNames) {
  const words = teamName.match(/[a-z0-9]+/gi) ?? [teamName];
  const base = words.length === 1 ? words[0].slice(0, 3) : words.map((word) => word[0]).join('').slice(0, 4);
  let candidate = base.toUpperCase() || 'TM';
  let suffix = 2;

  while (usedShortNames.has(normalize(candidate))) {
    candidate = `${base.toUpperCase().slice(0, 3)}${suffix}`;
    suffix += 1;
  }

  return candidate;
}

function clean(value) {
  return String(value ?? '').trim().replace(/\s+/g, ' ');
}

function normalize(value) {
  return clean(value).toLowerCase();
}

function sqlValue(value) {
  if (value === null || value === undefined) return 'null';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'null';
  return `'${String(value).replaceAll("'", "''")}'`;
}

function sqlBool(value) {
  return value ? 'true' : 'false';
}
