-- Finalize Match pipeline:
-- 1) freeze player CI when the official roster snapshot is created;
-- 2) record explicit non-contest scoring adjustments;
-- 3) finalize the persisted draft result and CI facts atomically.

create table if not exists public.launch_match_structural_points (
  id bigint generated by default as identity primary key,
  match_id text not null references public.launch_schedule_matches(id) on delete cascade,
  awarded_team_id text not null references public.launch_teams(id) on delete restrict,
  category text not null check (category in ('NoShow', 'WomenBonus', 'Penalty', 'Other')),
  points numeric not null check (points > 0 and mod(points * 2, 1) = 0),
  note text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (match_id, awarded_team_id, category)
);

alter table public.launch_match_structural_points enable row level security;

grant select, insert, update, delete on public.launch_match_structural_points to authenticated;

drop policy if exists "commissioners read match structural points" on public.launch_match_structural_points;
create policy "commissioners read match structural points"
on public.launch_match_structural_points
for select
to authenticated
using ((select private.is_launch_commissioner()));

drop policy if exists "commissioners insert draft match structural points" on public.launch_match_structural_points;
create policy "commissioners insert draft match structural points"
on public.launch_match_structural_points
for insert
to authenticated
with check (
  (select private.is_launch_commissioner())
  and not exists (
    select 1 from public.clash_match_publications publication
    where publication.match_id = launch_match_structural_points.match_id
  )
);

drop policy if exists "commissioners update draft match structural points" on public.launch_match_structural_points;
create policy "commissioners update draft match structural points"
on public.launch_match_structural_points
for update
to authenticated
using (
  (select private.is_launch_commissioner())
  and not exists (
    select 1 from public.clash_match_publications publication
    where publication.match_id = launch_match_structural_points.match_id
  )
)
with check (
  (select private.is_launch_commissioner())
  and not exists (
    select 1 from public.clash_match_publications publication
    where publication.match_id = launch_match_structural_points.match_id
  )
);

drop policy if exists "commissioners delete draft match structural points" on public.launch_match_structural_points;
create policy "commissioners delete draft match structural points"
on public.launch_match_structural_points
for delete
to authenticated
using (
  (select private.is_launch_commissioner())
  and not exists (
    select 1 from public.clash_match_publications publication
    where publication.match_id = launch_match_structural_points.match_id
  )
);

create or replace function private.current_clash_algorithm_version()
returns text
language sql
immutable
set search_path = ''
as $function$
  select '2026-27-v1-d100-exp1.8-move2-28-home15-doubles80-20-move50-neutral'::text
$function$;

revoke all on function private.current_clash_algorithm_version() from public;

create or replace function private.capture_clash_rating_snapshot_from_roster_player()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
declare
  scheduled_home_team_id text;
  scheduled_away_team_id text;
  course_home_team_id text;
  player_row public.launch_players%rowtype;
  resolved_ci integer;
  resolved_source text;
  resolved_side text;
  resolved_venue text;
begin
  select match_row.home_team_id, match_row.away_team_id, course.home_team_id
    into scheduled_home_team_id, scheduled_away_team_id, course_home_team_id
  from public.launch_schedule_matches match_row
  left join public.launch_courses course on course.id = match_row.course_id
  where match_row.id = new.match_id;

  if scheduled_home_team_id is null or scheduled_away_team_id is null then
    raise exception 'Cannot freeze Clash Index before both scheduled teams are assigned.'
      using errcode = '23514';
  end if;

  resolved_side := case
    when new.team_id = scheduled_home_team_id then 'Home'
    when new.team_id = scheduled_away_team_id then 'Away'
    else null
  end;

  if resolved_side is null then
    raise exception 'Official roster team does not match the scheduled Matchday teams.'
      using errcode = '23514';
  end if;

  select * into player_row
  from public.launch_players
  where id = new.player_id;

  if player_row.id is null then
    raise exception 'Official roster player does not exist.'
      using errcode = '23503';
  end if;

  resolved_ci := coalesce(
    player_row.clash_index,
    player_row.pdga_rating,
    case player_row.gender
      when 'Female' then 700
      when 'Male' then 825
      else null
    end
  );

  if resolved_ci is null or resolved_ci <= 0 then
    raise exception 'Official roster player % has no usable Clash Index seed.', new.player_id
      using errcode = '23514';
  end if;

  resolved_source := case
    when player_row.clash_index is null or player_row.clash_index_provisional then 'GhostAverage'
    else 'Established'
  end;

  resolved_venue := case
    when course_home_team_id is not null and course_home_team_id = scheduled_home_team_id then 'Home'
    else 'Neutral'
  end;

  insert into public.clash_match_rating_snapshots (
    match_id,
    player_id,
    team_id,
    player_name,
    team_name,
    side,
    venue,
    clash_index_before,
    ci_source_before,
    algorithm_version,
    captured_at
  )
  values (
    new.match_id,
    new.player_id,
    new.team_id,
    new.player_name_snapshot,
    new.team_name_snapshot,
    resolved_side,
    resolved_venue,
    resolved_ci,
    resolved_source,
    private.current_clash_algorithm_version(),
    coalesce(new.created_at, now())
  )
  on conflict (match_id, player_id) do nothing;

  return new;
end;
$function$;

revoke all on function private.capture_clash_rating_snapshot_from_roster_player() from public;

drop trigger if exists capture_clash_rating_snapshot_from_roster_player
  on public.launch_match_roster_snapshot_players;
create trigger capture_clash_rating_snapshot_from_roster_player
after insert on public.launch_match_roster_snapshot_players
for each row execute function private.capture_clash_rating_snapshot_from_roster_player();

create or replace function private.clash_ci_delta(
  actual numeric,
  expected numeric,
  contest_format text
)
returns integer
language plpgsql
immutable
set search_path = ''
as $function$
declare
  surprise numeric;
  raw_movement numeric;
  bounded_movement numeric;
  base_delta integer;
begin
  if expected < 0 or expected > 1 then
    raise exception 'Expected points must be between zero and one.'
      using errcode = '22023';
  end if;

  surprise := actual - expected;
  if surprise = 0 then
    return 0;
  end if;

  raw_movement := 28 * power(abs(surprise), 1.8);
  bounded_movement := least(28, greatest(2, raw_movement));
  base_delta := sign(surprise)::integer * round(bounded_movement)::integer;

  if contest_format = 'Doubles' then
    return sign(base_delta)::integer * round(abs(base_delta) * 0.5)::integer;
  end if;

  return base_delta;
end;
$function$;

revoke all on function private.clash_ci_delta(numeric, numeric, text) from public;

create or replace function public.finalize_clash_match_result(p_match_id text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $function$
declare
  result_row public.launch_match_results%rowtype;
  match_row public.launch_schedule_matches%rowtype;
  v_now timestamptz := now();
  v_algorithm_version text := private.current_clash_algorithm_version();
  v_venue text;
  v_snapshot_count integer;
  v_fact_count integer;
  v_player_update_count integer;
  v_contest_home_points numeric := 0;
  v_contest_away_points numeric := 0;
  v_structural_home_points numeric := 0;
  v_structural_away_points numeric := 0;
  v_expected_home_score numeric := 0;
  v_expected_away_score numeric := 0;
  v_automatic_home_points numeric := 0;
  v_automatic_away_points numeric := 0;
begin
  if current_user not in ('postgres', 'service_role') then
    if auth.uid() is null or not private.is_launch_commissioner() then
      raise exception 'Approved commissioner access is required.'
        using errcode = '42501';
    end if;
  end if;

  if p_match_id is null or btrim(p_match_id) = '' then
    raise exception 'A match id is required.'
      using errcode = '22023';
  end if;

  select * into result_row
  from public.launch_match_results
  where match_id = p_match_id
  for update;

  if result_row.match_id is null then
    raise exception 'Save the result as a draft before finalizing.'
      using errcode = '23503';
  end if;

  if result_row.status <> 'Draft' then
    raise exception 'Only a draft result can be finalized.'
      using errcode = '55000';
  end if;

  if result_row.home_score is null or result_row.away_score is null then
    raise exception 'Both official team scores are required before finalizing.'
      using errcode = '23514';
  end if;

  if exists (
    select 1 from public.clash_match_publications
    where match_id = p_match_id
  ) then
    raise exception 'This Matchday has already updated Clash Index.'
      using errcode = '23505';
  end if;

  select * into match_row
  from public.launch_schedule_matches
  where id = p_match_id;

  if match_row.id is null or match_row.home_team_id is null or match_row.away_team_id is null then
    raise exception 'The scheduled Matchday is incomplete.'
      using errcode = '23514';
  end if;

  select count(*), min(venue)
    into v_snapshot_count, v_venue
  from public.clash_match_rating_snapshots
  where match_id = p_match_id
    and algorithm_version = v_algorithm_version;

  if v_snapshot_count = 0 then
    raise exception 'No frozen pre-match Clash Index snapshot exists for this Matchday.'
      using errcode = '23514';
  end if;

  if (
    select count(distinct venue)
    from public.clash_match_rating_snapshots
    where match_id = p_match_id
      and algorithm_version = v_algorithm_version
  ) <> 1 then
    raise exception 'The frozen Matchday snapshot contains mixed venue classifications.'
      using errcode = '23514';
  end if;

  if exists (
    select 1
    from public.launch_result_contests contest
    join public.launch_result_contest_players player on player.contest_id = contest.id
    left join public.clash_match_rating_snapshots snapshot
      on snapshot.match_id = p_match_id
     and snapshot.player_id = player.player_id
     and snapshot.algorithm_version = v_algorithm_version
    where contest.match_id = p_match_id
      and snapshot.player_id is null
  ) then
    raise exception 'At least one result player is missing the frozen pre-match Clash Index snapshot.'
      using errcode = '23514';
  end if;

  if exists (
    select 1
    from public.launch_result_contests contest
    join public.launch_result_contest_players player on player.contest_id = contest.id
    where contest.match_id = p_match_id
      and (
        (player.side = 'Home' and player.team_id <> match_row.home_team_id)
        or (player.side = 'Away' and player.team_id <> match_row.away_team_id)
      )
  ) then
    raise exception 'A result player is assigned to the wrong scheduled team.'
      using errcode = '23514';
  end if;

  select
    coalesce(sum(
      case
        when home_outcome = 'W' then case when format = 'Singles' then 1 else 2 end
        when home_outcome = 'T' then case when format = 'Singles' then 0.5 else 1 end
        else 0
      end
    ), 0),
    coalesce(sum(
      case
        when away_outcome = 'W' then case when format = 'Singles' then 1 else 2 end
        when away_outcome = 'T' then case when format = 'Singles' then 0.5 else 1 end
        else 0
      end
    ), 0)
    into v_contest_home_points, v_contest_away_points
  from public.launch_result_contests
  where match_id = p_match_id;

  select
    coalesce(sum(points) filter (where awarded_team_id = match_row.home_team_id), 0),
    coalesce(sum(points) filter (where awarded_team_id = match_row.away_team_id), 0)
    into v_structural_home_points, v_structural_away_points
  from public.launch_match_structural_points
  where match_id = p_match_id;

  select
    coalesce(sum(
      greatest(
        (case when contest.format = 'Singles' then 1 else 2 end)
        - counts.away_players,
        0
      )
    ), 0),
    coalesce(sum(
      greatest(
        (case when contest.format = 'Singles' then 1 else 2 end)
        - counts.home_players,
        0
      )
    ), 0)
    into v_automatic_home_points, v_automatic_away_points
  from public.launch_result_contests contest
  join lateral (
    select
      count(*) filter (where player.side = 'Home')::integer as home_players,
      count(*) filter (where player.side = 'Away')::integer as away_players
    from public.launch_result_contest_players player
    where player.contest_id = contest.id
  ) counts on true
  where contest.match_id = p_match_id;

  v_expected_home_score := v_contest_home_points + v_structural_home_points;
  v_expected_away_score := v_contest_away_points + v_structural_away_points;

  if result_row.home_score <> v_expected_home_score
     or result_row.away_score <> v_expected_away_score then
    raise exception
      'Score audit failed. Matchups + reviewed adjustments produce %-% but the official score is %-%.',
      v_expected_home_score,
      v_expected_away_score,
      result_row.home_score,
      result_row.away_score
      using errcode = '23514';
  end if;

  create temporary table if not exists pg_temp.finalize_clash_facts (
    contest_id text,
    player_id text,
    team_id text,
    player_name text,
    team_name text,
    side text,
    venue text,
    format text,
    outcome text,
    clash_index_before integer,
    opponent_effective_ci numeric,
    win_probability numeric,
    actual_points numeric,
    expected_points numeric,
    performance_vs_expected numeric,
    ci_delta integer
  ) on commit drop;

  truncate pg_temp.finalize_clash_facts;

  insert into pg_temp.finalize_clash_facts (
    contest_id,
    player_id,
    team_id,
    player_name,
    team_name,
    side,
    venue,
    format,
    outcome,
    clash_index_before,
    opponent_effective_ci,
    win_probability,
    actual_points,
    expected_points,
    performance_vs_expected,
    ci_delta
  )
  with contest_counts as (
    select
      contest.id as contest_id,
      contest.format,
      count(player.player_id) filter (where player.side = 'Home') as home_players,
      count(player.player_id) filter (where player.side = 'Away') as away_players
    from public.launch_result_contests contest
    left join public.launch_result_contest_players player on player.contest_id = contest.id
    where contest.match_id = p_match_id
    group by contest.id, contest.format
  ),
  rated_contests as (
    select contest.*
    from public.launch_result_contests contest
    join contest_counts counts on counts.contest_id = contest.id
    where contest.match_id = p_match_id
      and (
        (contest.format = 'Singles' and counts.home_players = 1 and counts.away_players = 1)
        or
        (contest.format = 'Doubles' and counts.home_players = 2 and counts.away_players = 2)
      )
  ),
  side_strength as (
    select
      contest.id as contest_id,
      contest.format,
      player.side,
      case
        when contest.format = 'Singles' then max(snapshot.clash_index_before)::numeric
        else
          0.8 * max(snapshot.clash_index_before)::numeric
          + 0.2 * min(snapshot.clash_index_before)::numeric
      end as base_ci
    from rated_contests contest
    join public.launch_result_contest_players player on player.contest_id = contest.id
    join public.clash_match_rating_snapshots snapshot
      on snapshot.match_id = p_match_id
     and snapshot.player_id = player.player_id
     and snapshot.algorithm_version = v_algorithm_version
    group by contest.id, contest.format, player.side
  ),
  contest_probability as (
    select
      contest.id as contest_id,
      contest.format,
      home_strength.base_ci as home_base_ci,
      away_strength.base_ci as away_base_ci,
      case
        when contest.format = 'Singles' and v_venue = 'Home'
          then home_strength.base_ci + 15
        else home_strength.base_ci
      end as home_effective_ci,
      away_strength.base_ci as away_effective_ci
    from rated_contests contest
    join side_strength home_strength
      on home_strength.contest_id = contest.id and home_strength.side = 'Home'
    join side_strength away_strength
      on away_strength.contest_id = contest.id and away_strength.side = 'Away'
  ),
  expanded as (
    select
      contest.id as contest_id,
      player.player_id,
      player.team_id,
      snapshot.player_name,
      snapshot.team_name,
      player.side,
      v_venue as venue,
      contest.format,
      case when player.side = 'Home' then contest.home_outcome else contest.away_outcome end as outcome,
      snapshot.clash_index_before,
      case
        when player.side = 'Home' then probability.away_effective_ci
        else probability.home_effective_ci
      end as opponent_effective_ci,
      case
        when player.side = 'Home' then
          1 / (1 + power(10::numeric, ((probability.away_effective_ci - probability.home_effective_ci) / 100)::numeric))
        else
          1 / (1 + power(10::numeric, ((probability.home_effective_ci - probability.away_effective_ci) / 100)::numeric))
      end as win_probability
    from rated_contests contest
    join contest_probability probability on probability.contest_id = contest.id
    join public.launch_result_contest_players player on player.contest_id = contest.id
    join public.clash_match_rating_snapshots snapshot
      on snapshot.match_id = p_match_id
     and snapshot.player_id = player.player_id
     and snapshot.algorithm_version = v_algorithm_version
  ),
  scored as (
    select
      expanded.*,
      case expanded.outcome
        when 'W' then 1::numeric
        when 'T' then 0.5::numeric
        else 0::numeric
      end as actual_points
    from expanded
  )
  select
    scored.contest_id,
    scored.player_id,
    scored.team_id,
    scored.player_name,
    scored.team_name,
    scored.side,
    scored.venue,
    scored.format,
    scored.outcome,
    scored.clash_index_before,
    scored.opponent_effective_ci,
    scored.win_probability,
    scored.actual_points,
    scored.win_probability,
    scored.actual_points - scored.win_probability,
    private.clash_ci_delta(scored.actual_points, scored.win_probability, scored.format)
  from scored;

  select count(*) into v_fact_count
  from pg_temp.finalize_clash_facts;

  if v_fact_count = 0 then
    raise exception 'No complete CI-rated singles or doubles contests were found.'
      using errcode = '23514';
  end if;

  if exists (
    select 1
    from (
      select distinct fact.player_id, fact.clash_index_before
      from pg_temp.finalize_clash_facts fact
    ) fact
    join public.launch_players player on player.id = fact.player_id
    where player.clash_index is not null
      and player.clash_index <> fact.clash_index_before
  ) then
    raise exception 'A player Clash Index changed after the frozen Matchday snapshot. Use the correction workflow before finalizing.'
      using errcode = '40001';
  end if;

  update public.launch_match_results
  set status = 'Published',
      published_at = v_now,
      updated_at = v_now
  where match_id = p_match_id;

  insert into public.clash_contest_rating_facts (
    contest_id,
    match_id,
    player_id,
    team_id,
    player_name,
    team_name,
    side,
    venue,
    format,
    outcome,
    clash_index_before,
    opponent_effective_ci,
    win_probability,
    actual_points,
    expected_points,
    performance_vs_expected,
    ci_delta,
    algorithm_version,
    calculated_at
  )
  select
    fact.contest_id,
    p_match_id,
    fact.player_id,
    fact.team_id,
    fact.player_name,
    fact.team_name,
    fact.side,
    fact.venue,
    fact.format,
    fact.outcome,
    fact.clash_index_before,
    fact.opponent_effective_ci,
    fact.win_probability,
    fact.actual_points,
    fact.expected_points,
    fact.performance_vs_expected,
    fact.ci_delta,
    v_algorithm_version,
    v_now
  from pg_temp.finalize_clash_facts fact;

  perform set_config('app.clash_rating_engine_write', 'on', true);

  with totals as (
    select
      player_id,
      min(clash_index_before) as clash_index_before,
      sum(ci_delta)::integer as total_delta
    from pg_temp.finalize_clash_facts
    group by player_id
  ),
  sources as (
    select player_id, ci_source_before
    from public.clash_match_rating_snapshots
    where match_id = p_match_id
      and algorithm_version = v_algorithm_version
  )
  update public.launch_players player
  set clash_index = totals.clash_index_before + totals.total_delta,
      clash_index_provisional = (sources.ci_source_before = 'GhostAverage'),
      updated_at = v_now
  from totals
  join sources on sources.player_id = totals.player_id
  where player.id = totals.player_id;

  perform set_config('app.clash_rating_engine_write', 'off', true);

  select count(distinct player_id)
    into v_player_update_count
  from pg_temp.finalize_clash_facts;

  insert into public.clash_match_publications (
    match_id,
    algorithm_version,
    snapshot_count,
    fact_count,
    player_update_count,
    published_at
  )
  values (
    p_match_id,
    v_algorithm_version,
    v_snapshot_count,
    v_fact_count,
    v_player_update_count,
    v_now
  );

  return jsonb_build_object(
    'matchId', p_match_id,
    'algorithmVersion', v_algorithm_version,
    'snapshots', v_snapshot_count,
    'facts', v_fact_count,
    'playersUpdated', v_player_update_count,
    'contestHomePoints', v_contest_home_points,
    'contestAwayPoints', v_contest_away_points,
    'automaticHomePoints', v_automatic_home_points,
    'automaticAwayPoints', v_automatic_away_points,
    'structuralHomePoints', v_structural_home_points,
    'structuralAwayPoints', v_structural_away_points,
    'homeScore', result_row.home_score,
    'awayScore', result_row.away_score,
    'publishedAt', v_now,
    'clashPulseReady', true
  );
exception when others then
  perform set_config('app.clash_rating_engine_write', 'off', true);
  raise;
end;
$function$;

revoke all on function public.finalize_clash_match_result(text) from public;
grant execute on function public.finalize_clash_match_result(text) to authenticated, service_role;

comment on table public.launch_match_structural_points is
  'Commissioner-reviewed team points outside the ordinary recorded contest outcomes, such as no-show penalties or women bonus points.';

comment on function public.finalize_clash_match_result(text) is
  'Commissioner-only atomic finalization: audits score math, publishes the result, persists immutable CI facts, updates player CI once, and marks Clash Pulse data ready.';
